version: '3'
services:
  supportbot:
    #build: .
    image: "bostrot/telegram-support-bot:4.0.0"
    restart: unless-stopped
    volumes:
      - ${PWD}/config:/bot/config
    ports:
      - "8080:8080"
