# bot testing
# bot_token: '5635494831:AAGKPEwcQ6ZQbT0H0safvRv_1mHRPFa2G5w' # support bot token
# staffchat_id: '-660283561' # eg. -123456789
# owner_id: '865580321'

# bot settings 
bot_token: 'BOT_TOKEN' # support bot token
staffchat_id: 'STAFFCHAT_ID' # eg. -123456789
owner_id: 'OWNER_ID'
spam_time: 5 * 60 * 1000 # time (in MS) in which user may send 5 messages
allow_private: true # Allow / disallow option for staff to chat privately
auto_close_tickets: false
direct_reply: true
anonymous_tickets: false #Include userid in tickets or not
show_auto_replied: false # Send auto replied msgs to staff chat
show_user_ticket: false # Show ticket id to user

parse_mode: 'MarkdownV2' # DO NOT CHANGE!

signal_enabled: false # Enable/disable signal
signal_number: '+12345689' # Your signal number / account

web_server: false # Enable/disable web server
web_server_port: 8080 # Port for web server

dev_mode: false # Enable/disable dev mode

# customize your language
language: 
  startCommandText: |
    Hei
    Boten er ikke i drift.
    Har du spørsmål, anbefaler vi deg å lese vår informasjon og FAQ på https://my.samvirk.com/
    Om du ikke finner svar på det du leter etter der, kan du kontakte oss på kontakt@samvirk.com
    
    Hello,
    The bot is not operational.
    If you have questions, we recommend that you read our information and FAQ at https://my.samvirk.com/
    If you do not find the answer to what you are looking for there, you can contact us at kontakt@samvirk.com
  faqCommandText: 'Les mer på https://my.samvirk.com/faq'
  helpCommandText: |
    Tilgjengelige kommandoer / Available commands:
    /help
    /faq
  contactMessage: |+
    Boten er ikke i drift.
    Har du spørsmål, anbefaler vi deg å lese vår informasjon og FAQ på https://my.samvirk.com/
    Om du ikke finner svar på det du leter etter der, kan du kontakte oss på kontakt@samvirk.com
        
    The bot is not operational.
    If you have questions, we recommend that you read our information and FAQ at https://my.samvirk.com/
    If you do not find the answer to what you are looking for there, you can contact us at kontakt@samvirk.com
  blockedSpam: 'You sent quite a number of questions in the last while. Please wait until staff reviews them.'
  ticket: 'Ticket'
  closed: 'closed'
  acceptedBy: 'was accepted by'
  dear: 'Hei'
  regards: 'Vennlig hilsen / Best regards,'
  from: 'from'
  language: 'Language'
  msg_sent: 'Message sent to user'
  file_sent: 'File sent to user'
  usr_with_ticket: 'User with ticket'
  banned: 'banned'
  replyPrivate: 'Reply in private'
  services: 'Select a service from the list below'
  customer: 'customer'
  msgForwarding: 'You messages will now be forwarded to vendors of the group: '
  back: 'Go back'
  whatSubCategory: 'Which subcategory describes your needs the best? '
  prvChatEnded: 'Private chat ended.'
  prvChatOpened: 'Private Chat opened with customer.'
  prvChatEnd: 'End Private chat'
  prvChatOpenedCustomer: 'Opened private chat'
  instructionsSent: 'Instructions were sent to you in private chat.'
  openTickets: 'Open Tickets'
  support: 'Support'
  prvChatOnly: 'This command can be used in private chat only.'
  ticketClosed: |+
    Saken din er avsluttet da boten ikke lengre er i drift.
    Har du spørsmål, anbefaler vi deg å lese vår informasjon og FAQ på https://my.samvirk.com/
    Om du ikke finner svar på det du leter etter der, kan du kontakte oss på kontakt@samvirk.com

    Your case is closed as the bot is no longer operational.
    If you have questions, we recommend you read our information and FAQ at https://my.samvirk.com/
    If you do not find the answer to what you are looking for there, you can contact us at kontakt@samvirk.com
  links: 'Direct support links'
  textFirst: |+
    Vennligst send oss et spørsmål før du sender et bilde. Da er det enklere for oss å hjelpe deg.
    
    Please send us a message before sending an image so that we can help you better.
  ticketClosedError: 'You cannot reply to a closed ticket.'
  automatedReply: 'This is an automated reply.'
  automatedReplyAuthor: 'BottyBot.'
  doesntHelp: 'This does not help.'
  automatedReplySent: 'Automated reply was send to the user.'
  ticketReopened: 'Ticket reopened.'

categories: []


