# bot testing
bot_token: '5635494831:AAGKPEwcQ6ZQbT0H0safvRv_1mHRPFa2G5w' # support bot token
staffchat_id: '-660283561' # eg. -123456789
owner_id: '865580321'

# bot settings
# bot_token: 'BOT_TOKEN', # support bot token
# staffchat_id: 'STAFFCHAT_ID', # eg. -123456789
# owner_id: 'OWNER_ID',
spam_time: 5 * 60 * 1000 # time (in MS) in which user may send 5 messages
allow_private: true # Allow / disallow option for staff to chat privately
auto_close_tickets: true
direct_reply: true
anonymous_tickets: false #Include userid in tickets or not
show_auto_replied: false # Send auto replied msgs to staff chat
show_user_ticket: false # Show ticket id to user

parse_mode: 'MarkdownV2' # DO NOT CHANGE!

signal_enabled: false # Enable/disable signal
signal_number: '+12345689' # Your signal number / account

web_server: false # Enable/disable web server
web_server_port: 8080 # Port for web server

dev_mode: false # Enable/disable dev mode

# customize your language
language: 
  startCommandText: "Velkommen til Samvirk Support!\n" +
  "Vi er her for å svare på det du lurer på om SAMVIRK! Fyr løs med spørsmål, men sjekk gjerne om svaret ditt allerede finnes på https://my.samvirk.com/faq.\n\n" +
  "Husk at svarene vi gir deg er rådgivende og veiledende. Det kan forekomme endringer i tiden fremover nå som produktet fremdeles er i utvikling.\n\n" +
  "// \n\n" +
  "Welcome to Samvirk Support!\n" +
  "We're here to answer all your questions about SAMVIRK! Come with it, but please check https://my.samvirk.com/faq to see if your question is already answered there.\n\n" +
  "Keep in mind that the answers we give you are advisory and guiding. There may be changes in the time ahead, considering that the product is still in development.",
  faqCommandText: 'Les mer på https://my.samvirk.com/faq'
  helpCommandText: 'Bare skriv et spørsmål til oss her i bot-en, så vil du få et svar fra oss.\n\nJust write a question to this bot, and you will get an answer from us.\n\n<b>Tilgjengelige kommandoer / Available commands:</b>\n/help\n/faq'
  contactMessage: 'Takk for meldingen. Du hører fra oss så snart som mulig.\n\nThank you for contacting us. We will answer as soon as possible.'
  blockedSpam: 'You sent quite a number of questions in the last while. Please wait until staff reviews them.'
  ticket: 'Ticket'
  closed: 'closed'
  acceptedBy: 'was accepted by'
  dear: 'Hei'
  regards: 'Vennlig hilsen / Best regards,'
  from: 'from'
  language: 'Language'
  msg_sent: 'Message sent to user'
  file_sent: 'File sent to user'
  usr_with_ticket: 'User with ticket'
  banned: 'banned'
  replyPrivate: 'Reply in private'
  services: 'Select a service from the list below'
  customer: 'customer'
  msgForwarding: 'You messages will now be forwarded to vendors of the group: '
  back: 'Go back'
  whatSubCategory: 'Which subcategory describes your needs the best? '
  prvChatEnded: 'Private chat ended.'
  prvChatOpened: 'Private Chat opened with customer.'
  prvChatEnd: 'End Private chat'
  prvChatOpenedCustomer: 'Opened private chat'
  instructionsSent: 'Instructions were sent to you in private chat.'
  openTickets: 'Open Tickets'
  support: 'Support'
  prvChatOnly: 'This command can be used in private chat only.'
  ticketClosed: 'Spørsmålet ditt ble merket som besvart. Dersom du fremdeles lurer på noe, kan du gjerne stille et nytt spørsmål.\n\nYour question was marked as resolved. If you still have any questions, please feel free to ask them here.'
  links: 'Direct support links'
  textFirst: 'Vennligst send oss et spørsmål før du sender et bilde. Da er det enklere for oss å hjelpe deg.\n\nPlease send us a message before sending an image so that we can help you better.'
  ticketClosedError: 'You cannot reply to a closed ticket.'
  automatedReply: 'This is an automated reply.'
  automatedReplyAuthor: 'BottyBot.'
  doesntHelp: 'This does not help.'
  automatedReplySent: 'Automated reply was send to the user.'
  ticketReopened: 'Ticket reopened.'

categories: []


